### ISSUE TITLE
看样子应该是生成成功了，但是好像没有写入到caches里面，QQ消息提示'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by VAHua** [Alpaca4610/nonebot-plugin-chatppt#1]

**Comment by Alpaca4610** [comment]
提供一下控制台的报错截图

**Comment by VAHua** [comment]
谢谢大佬回我！
这是我pycharm下的plugins
![image](https://user-images.githubusercontent.com/129832780/230899228-c13fd7cf-8934-44f4-b931-beb7882fca87.png)
![image](https://user-images.githubusercontent.com/129832780/230899840-8bb00cdc-1eaa-4cd9-8a48-d033b9a2fb6b.png)
我调用的时候直接发送的
![image](https://user-images.githubusercontent.com/129832780/230899344-d929e391-93fc-4354-8b4a-70d4625883ff.png)
这是返回的信息
![image](https://user-images.githubusercontent.com/129832780/230899443-98824cd9-917a-4df8-baf1-4133575b16bf.png)
后台没显示什么
![image](https://user-images.githubusercontent.com/129832780/230899623-8d4b2157-56cd-4846-bc7a-a76514b5f869.png)

**Comment by Alpaca4610** [comment]
在Bot目录下的data文件夹里面新建nonebot-plugin-chatppt文件夹。把PPT主题模版文件放进里面，并更名为theme.pptx
这一步你做了吗

**Comment by VAHua** [comment]
放了模板的，对模板有没有什么要求呢
![image](https://user-images.githubusercontent.com/129832780/231083224-d436ceb3-7d06-4f72-a8b8-f9299336077a.png)

**Comment by Alpaca4610** [comment]
奇怪......应该是在PPT生成的过程中出现了问题。你方便使用单步调试看一下是哪里出了问题吗

**Comment by VAHua** [comment]
好的大佬，我调试试试呢，排查一下问题，谢谢

**Comment by VAHua** [comment]
大佬，断点应该打哪个位置呢，我菜

**Comment by Alpaca4610** [comment]
> 大佬，断点应该打哪个位置呢，我菜

在__init__.py的第53行打

**Comment by VAHua** [comment]
消息获取到了
![image](https://user-images.githubusercontent.com/129832780/233281415-18465951-e9ea-4b39-8fde-ca4d9b4185f5.png)
这一步函数出错了
![image](https://user-images.githubusercontent.com/129832780/233282579-c7b5809f-5ee3-4418-9a34-e74bd5aa0d75.png)
![image](https://user-images.githubusercontent.com/129832780/233282858-e8bd9c8e-f101-4c86-84b6-bde1816c8f02.png)
![image](https://user-images.githubusercontent.com/129832780/233283098-7a0d930f-2aca-42f0-995c-a2c757512fa3.png)
看不懂是哪一步出错了呢

**Comment by Alpaca4610** [comment]
你调试的时候没有进入core.py里面嘛，你试可以在__init__.py的71行打断点，然后步入core.py里面看看是哪里出了问题。

**Comment by Feiyuyu0503** [comment]
+1，也遇到这个问题。是执行到这里报错 https://github.com/Alpaca4610/nonebot-plugin-chatppt/blob/1a439480537786b52e0dfcca1e6f6d7ba7a546b5/nonebot_plugin_chatppt/core.py#L121

**Comment by Alpaca4610** [comment]
> +1，也遇到这个问题。是执行到这里报错
> 
> https://github.com/Alpaca4610/nonebot-plugin-chatppt/blob/1a439480537786b52e0dfcca1e6f6d7ba7a546b5/nonebot_plugin_chatppt/core.py#L121

感觉像是Python-PPTX包创建幻灯片时出了问题，这个问题一直出现吗？报的错是不是和本issue题目的一样。

**Comment by Feiyuyu0503** [comment]
> > +1，也遇到这个问题。是执行到这里报错
> > https://github.com/Alpaca4610/nonebot-plugin-chatppt/blob/1a439480537786b52e0dfcca1e6f6d7ba7a546b5/nonebot_plugin_chatppt/core.py#L121
> 
> 感觉像是Python-PPTX包创建幻灯片时出了问题，这个问题一直出现吗？报的错是不是和本issue题目的一样。

一直是这个错。报的错一样

**Comment by Alpaca4610** [comment]
> > > +1，也遇到这个问题。是执行到这里报错
> > > https://github.com/Alpaca4610/nonebot-plugin-chatppt/blob/1a439480537786b52e0dfcca1e6f6d7ba7a546b5/nonebot_plugin_chatppt/core.py#L121
> > 
> > 
> > 感觉像是Python-PPTX包创建幻灯片时出了问题，这个问题一直出现吗？报的错是不是和本issue题目的一样。
> 
> 一直是这个错。报的错一样

提供一下你的Python-pptx包版本

**Comment by Feiyuyu0503** [comment]
> > > > +1，也遇到这个问题。是执行到这里报错
> > > > https://github.com/Alpaca4610/nonebot-plugin-chatppt/blob/1a439480537786b52e0dfcca1e6f6d7ba7a546b5/nonebot_plugin_chatppt/core.py#L121
> > > 
> > > 
> > > 感觉像是Python-PPTX包创建幻灯片时出了问题，这个问题一直出现吗？报的错是不是和本issue题目的一样。
> > 
> > 
> > 一直是这个错。报的错一样
> 
> 提供一下你的Python-pptx包版本

0.6.21

**Comment by VAHua** [comment]
忘记关了，今天才看到，哈哈，不好意思
