### ISSUE TITLE
可否支持多个主题自由调用

### ISSUE THREAD

**Issue by ElainaFanBoy** [Alpaca4610/nonebot-plugin-chatppt#2]
qwq

**Comment by Alpaca4610** [comment]
比如说指定某个主题生成？

**Comment by ElainaFanBoy** [comment]
> 比如说指定某个主题生成？

对，比如在目录下设定一个主题的文件夹，通过自定义主题文件名可以指定调用（？）

**Comment by Alpaca4610** [comment]
> > 比如说指定某个主题生成？
> 
> 对，比如在目录下设定一个主题的文件夹，通过自定义主题文件名可以指定调用（？）

OK，有时间我改改代码

**Comment by ElainaFanBoy** [comment]
> > > 比如说指定某个主题生成？
> > 
> > 对，比如在目录下设定一个主题的文件夹，通过自定义主题文件名可以指定调用（？）
> 
> OK，有时间我改改代码

辛苦，感谢大佬

**Comment by Alpaca4610** [comment]
已添加
