### ISSUE TITLE
[参数个数对不上]generate_ppt() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by Lptr-byte** [Alpaca4610/nonebot-plugin-chatppt#5]
![image](https://user-images.githubusercontent.com/54620759/236285144-dd11c5da-7e05-495a-a9b8-a985b83c14e2.png)

**Comment by Alpaca4610** [comment]
你的PPT模版文件是这个名字吗？

**Comment by Alpaca4610** [comment]
你使用的是最新的代码吗？

**Comment by Lptr-byte** [comment]
> 你使用的是最新的代码吗？

是的，这是我的各项依赖版本
```
python = "^3.10" 
 nonebot2 = "^2.0.0rc4" 
 nonebot-adapter-onebot = "^2.2.2" 
 openai = "^0.27.6" 
 python-pptx = "^0.6.21" 
 icrawler = "^0.6.6"
```

**Comment by Alpaca4610** [comment]
抱歉，之前git出了一些问题导致代码没有同步，目前已修复，使用仓库中的最新代码即可。pypi也已更新，可能需要时间同步。

**Comment by Lptr-byte** [comment]
> 抱歉，之前git出了一些问题导致代码没有同步，目前已修复，使用仓库中的最新代码即可。pypi也已更新，可能需要时间同步。

好的，已经可以用了（好耶）
