### ISSUE TITLE
请问大佬关于模板的问题

### ISSUE THREAD

**Issue by ElainaFanBoy** [Alpaca4610/nonebot-plugin-chatppt#6]
我在使用模板后生成的PPT背景是完全空白的，请问这是模板的问题吗，标准的模板应该是什么样子的

**Comment by Alpaca4610** [comment]
> 

我用的是我们学校的上课PPT模版，格式为PPTX，你试试其他的模版看看

**Comment by ElainaFanBoy** [comment]
> 

我这边的模板貌似除了背景在生成的时候所有其它元素全被删掉了，我试了一下直接把模板做成图片形式插到背景再生成就可以了
